services:
  - type: web
    name: aiva-detect-bot
    env: python
    region: singapore  # Choose a region closest to your users
    plan: free  # Or 'standard' for production
    buildCommand: |
      pip install -r requirements.txt
      python -c "from database.database import Base, engine; Base.metadata.create_all(bind=engine)"
    startCommand: python bot.py
    envVars:
      - key: RENDER
        value: true
      - key: WEBHOOK_MODE
        value: "true"
      - key: BOT_TOKEN
        fromService:
          type: secret
          name: BOT_TOKEN
      - key: DATABASE_URL
        value: sqlite:///data/aiva_detect.db
      - key: LOG_LEVEL
        value: DEBUG
      - key: ADMIN_IDS
        value: ""  # Set your admin Telegram IDs here, comma-separated
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: PORT
        value: 10000
        fromService:
          type: secret
          name: WEBHOOK_URL
      - key: WEBHOOK_SECRET
        fromService:
          type: secret
          name: WEBHOOK_SECRET
    plan: free
